DECLARE
CNT NUMBER;
BEGIN
SELECT COUNT(*) INTO CNT FROM COMPONENT WHERE NAME = 'L01';
IF CNT =0 THEN
   INSERT INTO COMPONENT(ID, NAME, FULLY_QUALIFIED_TYPE_NAME) 
   VALUES (COMPONENT_SQ.NEXTVAL,'L01','PayMedia.Integration.IFComponents.BBCL.Logistics.L01,PayMedia.Integration.IFComponents.BBCL.Logistics');
END IF;
commit;

END;
/
